/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author USER
 */
public class Resister extends javax.swing.JFrame {

    /**
     * Creates new form Resister
     */
    public Resister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title2 = new javax.swing.JLabel();
        name = new javax.swing.JButton();
        address = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        gmail = new javax.swing.JButton();
        password = new javax.swing.JButton();
        enteringName = new javax.swing.JTextField();
        enteringAddress = new javax.swing.JTextField();
        enteringContact = new javax.swing.JTextField();
        enteringGmail = new javax.swing.JTextField();
        enteringpassword = new javax.swing.JPasswordField();
        resister = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 153, 102));
        title2.setText("                                                           Online Train Tickets Management System");
        title2.setPreferredSize(new java.awt.Dimension(1229, 26));
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 44));

        name.setBackground(new java.awt.Color(153, 153, 153));
        name.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        name.setText("Name:");
        name.setToolTipText("");
        name.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 157, -1));

        address.setBackground(new java.awt.Color(153, 153, 153));
        address.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        address.setText("Address:");
        address.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 157, -1));

        contact.setBackground(new java.awt.Color(153, 153, 153));
        contact.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        contact.setText("Contact No:");
        contact.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 36));

        gmail.setBackground(new java.awt.Color(153, 153, 153));
        gmail.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        gmail.setText("Gmail ID:");
        gmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 157, 34));

        password.setBackground(new java.awt.Color(153, 153, 153));
        password.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        password.setText("Password:");
        password.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 157, 40));

        enteringName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        enteringName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteringNameActionPerformed(evt);
            }
        });
        getContentPane().add(enteringName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 350, 39));

        enteringAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteringAddressActionPerformed(evt);
            }
        });
        getContentPane().add(enteringAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 350, 39));
        getContentPane().add(enteringContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 350, 36));

        enteringGmail.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        getContentPane().add(enteringGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 350, -1));

        enteringpassword.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        getContentPane().add(enteringpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 350, 40));

        resister.setBackground(new java.awt.Color(0, 0, 0));
        resister.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        resister.setForeground(new java.awt.Color(0, 102, 102));
        resister.setText("   Resister");
        getContentPane().add(resister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 313, 62));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1.setText("  Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 160, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 102));
        jButton2.setText("  Sign in");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void enteringAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteringAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteringAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Homepage.main(new String[0]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enteringNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteringNameActionPerformed
        
    }//GEN-LAST:event_enteringNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Name=enteringName.getText();
        String Address=enteringAddress.getText();
        String Contact =enteringContact.getText();
        String Mail=enteringGmail.getText();
        String Password=enteringpassword.getText();
      
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
           try (
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookticket","root","")) {
               PreparedStatement ps=con.prepareStatement("insert into accountinfo(Name,Address,Contact,Mail,Password) values(?,?,?,?,?)");
               ps.setString(1,Name);
               ps.setString(2, Address);
               ps.setString(3, Contact);
               ps.setString(4, Mail);
               ps.setString(5, Password);
               ps.execute();
           }
        this.dispose();
            
        Book_ticket.main(new String[0]);
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton address;
    private javax.swing.JButton contact;
    private javax.swing.JTextField enteringAddress;
    private javax.swing.JTextField enteringContact;
    private javax.swing.JTextField enteringGmail;
    private javax.swing.JTextField enteringName;
    private javax.swing.JPasswordField enteringpassword;
    private javax.swing.JButton gmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton name;
    private javax.swing.JButton password;
    private javax.swing.JLabel resister;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
